name: petnity
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: '>=2.19.3 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  flutter_parsed_text: ^2.2.1
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.2.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.3.0
  equatable: ^2.0.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  retry: ^3.1.0
  flutter_secure_storage: ^9.0.0
  
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  agora_uikit: ^1.3.7
  flutterwave_standard: ^1.0.8
  uuid: ^3.0.7
  number_paginator: ^0.4.0
  csc_picker: ^0.2.7
  flutter_phone_direct_caller: ^2.1.1
   
  flutter_tawkto: ^0.0.2
  flutter_html: ^3.0.0-beta.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.2.0
  url_launcher: ^6.2.4
  firebase_database: ^10.4.6
  firebase_storage: ^11.6.6
  permission_handler: ^11.3.0
  image_cropper: ^5.0.1
  chat_bubbles: ^1.5.0
  
    
dev_dependencies:
  change_app_package_name: ^1.1.0 
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


  flutter_lints: ^2.0.0
  
  flutter_launcher_icons: ^0.13.1


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/svgs/
    - assets/images/gifs/

  
  fonts:
    - family: InterSans
      fonts:
        - asset: fonts/Intersans-bold.otf
        - asset: fonts/intersans-regular.otf
       
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat_Bold.ttf
          weight: 700
        - asset: fonts/Montserrat_Regular.ttf
          weight: 400
        - asset: fonts/Montserrat_Italic.ttf
          style: italic
          weight: 400

    - family: Satoshi-Variable
      fonts:
        - asset: fonts/Satoshi-Light.otf
          weight: 400
        - asset: fonts/Satoshi-Medium.otf
          weight: 600
        - asset: fonts/Satoshi-Variable.ttf
          weight: 500
        - asset: fonts/Satoshi-Bold.otf
          weight: 700

        
             
  